In [1]:
import numpy as np
rng = np.random.RandomState(1234)

## データの用意

In [86]:
dir_name = './ml-100k/'
f = open(dir_name + 'u.info')
user_num, item_num = [(int)(li.split(" ")[0]) for li in f.readlines()[:-1]]
f.close()
R = np.zeros((user_num,item_num))
print R.shape
f = open(dir_name + 'u.data')
# lines = [ li.split("\t")[:-1] for li in f.readlines()]
lines = [map(lambda x: int(x), li.split("\t")[:-1]) for li in f.readlines()]
f.close()
for li in lines:
    R[li[0]-1,li[1]-1] = li[2]
# R[0:3,0:20]

(943, 1682)


\begin{equation*} \min_{p,q,b_u,b_i} \sum_{(u,i) \in R} (r_{u,i} - p_u q^{T}_i - \mu - b_u - b_i)^{2} + \lambda ()^{2}\end{equation*}

In [117]:
def matrix_factorization(R,latent_dim = 20,alpha=0.05,lamb=0.1):
    # initialize parameter
    P = np.random.uniform(low=0.2,high =2,size=(R.shape[0],latent_dim))
    Q = np.random.uniform(low=0.2,high =2,size=(R.shape[1],latent_dim))
    mu = R.sum() / (R != 0).sum()
    b_u = R.sum(1) / (R != 0).sum(1) - mu #行(user)のbias
    print b_u
    b_i = R.sum(0) / (R != 0).sum(0) - mu #列(item)のbias
    
    for epoch in xrange(100000000000000000):
        #errの計算
        non_zero_index_of_R = np.argwhere(R != 0).T
        err = R; 
        # Rの0の要素は計算に含めない
        err[non_zero_index_of_R[0],non_zero_index_of_R[1]] -= np.dot(P,Q.T)[non_zero_index_of_R[0],non_zero_index_of_R[1]]
        #update
        b_u += alpha * (err.sum(1) - err.shape[1] * lamb * b_u)
        b_i  += alpha * (err.sum(0) - err.shape[0] * lamb * b_i)
        Q += alpha * (np.dot(err.T,P) - err.shape[0] * lamb * Q)
        P += alpha * (np.dot(err,Q) - err.shape[1] * lamb * P)
        
        print P
        print Q
        return np.dot(P,Q.T)
        
    
    
    

## 練習

In [119]:
latent_dim = 2

P = np.random.uniform(low=0,high =1,size=(R.shape[0],latent_dim))
Q = np.random.uniform(low=0,high =1,size=(R.shape[1],latent_dim))

R = np.array([
    [3,3,4,5,0,2,0,0,0,3],
    [2,0,0,4,0,0,2,0,0,0],
    [0,3,5,0,0,0,0,0,4,3],
    [3,0,0,4,2,0,1,1,0,0],],dtype="float32")
# print(R.sum(1) / (R != 0).sum(1)) 
# print(R.sum(0) / (R != 0).sum(0)) 
# print(R.sum() / (R != 0).sum()) 

print R
print "-----" * 5
ans = matrix_factorization(R,3)
print np.around(ans)
# non_zero_index_of_R = np.argwhere(R != 0)
# err = R
# print err
# err[non_zero_index_of_R.T[0], non_zero_index_of_R.T[1]] = np.dot(P,Q.T)[non_zero_index_of_R.T[0], non_zero_index_of_R.T[1]]
# print err
# print err.shape
# print non_zero_index_of_R.T
# print R[non_zero_index_of_R.T[0], non_zero_index_of_R.T[1]]

# np.where(R != 0)

[[ 3.  3.  4.  5.  0.  2.  0.  0.  0.  3.]
 [ 2.  0.  0.  4.  0.  0.  2.  0.  0.  0.]
 [ 0.  3.  5.  0.  0.  0.  0.  0.  4.  3.]
 [ 3.  0.  0.  4.  2.  0.  1.  1.  0.  0.]]
-------------------------
[ 0.33333333 -0.33333333  0.75       -0.8       ]
[[ 0.63510465  0.60692334  1.49122602]
 [ 0.3582865   1.52820319  1.16470942]
 [ 0.90453399  0.80903537  1.59454879]
 [ 0.34159817  0.58756689  1.09758428]]
[[ 0.34725749  0.46167346  1.41098681]
 [ 1.36293721  1.55364588  1.2003743 ]
 [ 1.84210721  0.50497625  0.88417147]
 [ 1.48816727  1.59674314  1.384281  ]
 [ 0.20594772  1.23799415  1.01811018]
 [ 1.71983417  1.73708618  0.6778229 ]
 [ 1.05148981  0.19234431  0.70680948]
 [ 1.19652705  0.74578995  0.26346632]
 [ 1.53995301  1.1451043   0.48956303]
 [ 1.02615642  0.42060547  1.18556789]]
[[ 3.  4.  3.  4.  2.  3.  2.  2.  2.  3.]
 [ 2.  4.  2.  5.  3.  4.  1.  2.  3.  2.]
 [ 3.  4.  3.  5.  3.  4.  2.  2.  3.  3.]
 [ 2.  3.  2.  3.  2.  2.  1.  1.  2.  2.]]
